Repository martin-helmich/prometheus-nginxlog-exporter, pull requests merged in 2020-05, with the labels that each got.

#115 Add option to change metrics endpoint
  README.adoc
  config/loader_flags.go
  config/structs.go
  example-config.hcl
  go.sum
  main.go
Labels: enhancement

#117 Fix custom endpoint, 3rd time's the charm
  config/structs.go
  features/custom_endpoint.feature
  features/steps/steps.py
  features/test-config-custom-endpoint.yaml
  go.mod
  go.sum
  main.go
Labels: bug

#119 Document replacement behavior for relabeling
  README.adoc
  relabeling/mapping_test.go
Labels: documentation
